name: Dialogo de senha
description: Caixa de diálogo com um campo do tipo senha
title: "senha"
labels: ["password"]

body:

  - type: input
    id: _
    attributes:
      label: Qual o arquivo .desktop responsável pelo aplicativo?
      description: Esse é o arquivo responsável por iniciar o aplicativo ele fica localizado um `/usr/share/applications/` ou em `/usr/share/tiger/xfce-config/applications/` (caso escolha `Exibir um aplicativo que foi oculto`)
      placeholder: "org.kde.kwrite.desktop"
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Onde os parametros extras devem ser adicionados?
      description: Diga o que você quer fazer com o aplicativo
      options:
        - Como primeiro parametro
        - Como último parametro
        - Antes do comando
    validations:
      required: true
  - type: input
    id: new_name
    attributes:
      label: Qual o novo nome
      description: "Caso tenha escolhido `Definir um nome manualmente` digite o nome sugerido no campo abaixo"
      placeholder: "Editor de textos"
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: "Termo de bom senso"
      description: Você confirma que não está enviando sugestão de conteúdo racista, sexista, sexual, gore, apologia a violência, preferência política ou conteúdo sensível e/ou proíbido para menores de 18 anos?
      options:
        - label: Sim, não estou
          required: true
