name: Dialogo de senha
description: Caixa de diálogo com um campo do tipo senha
title: "senha"
labels: ["password"]

body:

  - type: input
    id: _
    attributes:
      label: Qual o arquivo .desktop responsável pelo aplicativo?
      description: Esse é o arquivo responsável por iniciar o aplicativo ele fica localizado um `/usr/share/applications/` ou em `/usr/share/tiger/xfce-config/applications/` (caso escolha `Exibir um aplicativo que foi oculto`)
      placeholder: "org.kde.kwrite.desktop"
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Onde os parametros extras devem ser adicionados?
      description: Você pode especificar onde os parámetros devem ser adicionados, como primeiro parâmetro irá ser adicionado logo após o comando, ao final será adicionado como último parâmetro e antes como um envólucro, use essa opção somente como último recurso
      options:
        - Como primeiro parametro
        - Como último parametro
        - Antes do comando
    validations:
      required: true
  - type: input
    id: new_name
    attributes:
      label: Quais os novos parametros?
      description: "Aqui você adiciona os novos parâmentros, caso utilize o caractere `|` lembre-se de adicionar um `\\` antes ficando assim: `\\|`"
      placeholder: ""
    validations:
      required: true
  - type: textarea
    id: Justificativa
    attributes:
      label: Justificativa
      description: Esse tipo de sugestão tem o potencial de abrir brechas de segurança, então precisamos saber o motivo de você sugerir isso para comparar com os resultados e poder analisar o risco x benefício
      placeholder: "Por que quer sugerir isso?"
      value: "Quero sugerir isso porque..."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: "Termo de bom senso"
      description: Você confirma que não está enviando sugestão de conteúdo racista, sexista, sexual, gore, apologia a violência, preferência política ou conteúdo sensível e/ou proíbido para menores de 18 anos?
      options:
        - label: Sim, não estou
          required: true
