name: Sugerir um patch
description: Sugira um patch para um arquivo .desktop
title: "Sugestão de ação"
labels: ["Sugestão"]

body:
  - type: input
    id: name_
    attributes:
      label: Qual o arquivo .desktop?
      description: Esse nome será exibido assim que o usuário digitar o padrão
      placeholder: "Listar arquivos"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Qual o tipo de patch você está sugerindo?
      description: Você pode escolher se sua ação vai ser abrir um URL no navegador, se será executar um comando no terminal ou se vai executar um aplicativo com interface gráfica
      options:
        - Ocultar um aplicativo
        - Exibir um aplicativo que foi oculto
        - Usar o nome genérico como nome
        - Definir um nome manualmente
    validations:
      required: true
  - type: input
    id: command_
    attributes:
      label: Qual o novo nome
      description: "Caso tenha escolhido 'Definir um nome manualmente' digite o nome sugerido no campo abaixo"
      placeholder: "Editor de textos"
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: "Termo de bom senso"
      description: Você confirma que não está enviando sugestão de conteúdo racista, sexista, sexual, gore, apologia a violência, preferência política ou conteúdo sensível e/ou proíbido para menores de 18 anos?
      options:
        - label: Sim, não estou
          required: true
