name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: sh ./build.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
       name: glib-2.0.tar.gz
       path: glib-2.0.tar.gz

